version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  safe-to-npm-release:
      executor:
        name: node/default
      steps:
        - checkout
        - run: npm install
        - run: npm run build
        - run: chmod 777 /usr/local/lib/node_modules/*
        - run: npm link mrules-engine
        - run: npm run check

workflows:
    build-and-test:
      jobs:
        - build-and-test
        - safe-to-npm-release